var trans_table = {
    'Light Armor': 'ライトアーマー',
    'Heavy Armor': 'ヘビーアーマー',
    'Caster Armor': '詠唱者用アーマー',
    'Required Physique': '要求体格',
    'Required Cunning': '要求狡猾性',
    'Required Spirit': '要求精神',
    'Required': '要求ステータス',
    'Grants Skill': 'アイテムスキル',
    'Bonus to All Pets': '全ペットへのボーナス',
    'Set bonus': 'セットボーナス',
    '([0-9]+)% Piercing': '$1% 装甲貫通',
    'Energy Absorption From Enemy Spells': '敵の呪文からエナジー吸収',
    'Offensive Ability': '攻撃能力',
    'Defensive Ability': '防御能力',
    'Damage Reflected': 'ダメージ反射',
    'Increased Experience': '経験値増加',
    'Chance to pass through Enemies': '貫通確率',
    '([0-9]+)% Chance to be Used': '通常攻撃時$1%の確率',
    '([0-9]+)% Chance on attacking': '攻撃時$1%の確率',
    '([0-9]+)% Chance on a critical attack ': 'クリティカル攻撃時$1%の確率',
    '([0-9]+)% Chance when hit by a melee attack': '近接攻撃被打時$1%の確率',
    '([0-9]+)% Chance when hit': '被打時$1%の確率',
    'Chance to Avoid Projectiles': '投射物回避率',
    'Chance to Avoid Melee Attacks': '近接攻撃回避率',
    'Chance for target to Fumble Attacks For ([0-9]+) Seconds?': 'の確率で標的は$1秒間近接攻撃を外す',
    'Chance of Impaired Aim to target For ([0-9]+) Seconds?': 'の確率で標的は$1秒間遠隔攻撃を外す',
    ' Chance of': 'の確率で ',
    'Skill Cooldown Reduction': 'クールダウン短縮',
    '(.+) With (.+) Improved Duration': '$1 $2 持続時間延長',
    'Reduced (.+) Duration': '$1時間短縮',
    ' Regenerated per second': '再生/s',
    '(.+) Reduced (.+) Retaliation': '$1$2減少報復',
    'Retaliate causing (.+) Reduction to Enemy\'s (.+)': '$2$1排出報復',
    'Reduction to Enemy\'s (.+)': '敵の$1減少',
    '(.+) Damage converted to (.+) Damage': '$1→$2 変換',
    'Increases (.+) Regeneration by ([0-9]+)%': '$2% $1再生量増加',
    'Increases Armor Absorption by ([0-9]+)%': '$1% 装甲吸収増加',
    'Active (.+) Cost per Second': '$1/s',
    ' Over ([0-9]+) Seconds': '/$1s',
    '([0-9]+) Per Second': '$1/s',
    'to All Skills in (.+)': '全$1スキル',
    'to All Skills': '全スキル',
    'Reduction in Life Leech Duration': 'ライフ吸収時間短縮',
    'Damage to (.+)': '$1へのダメージが増加',
    '(.+) target for (.+) Seconds': '$1を $2秒',
    '([0-9]+) Projectiles in a ([0-9]+)° Projectile Spread': '$1 砲弾数  $2°砲弾の広がり',
    'Reduced target\'s (.+)': '$1減少',
    ' of (.+) converted to (.+)': '$1を$2に変換',
    ' Disrupt target\'s skills': '標的のスキル妨害',
    ' Second Duration': '秒 持続時間',
    ' Seconds? Skill Recharge': '秒 スキルリチャージ',
    ' Less Damage From (.+)': '$1からのダメージ減少',
    ' Speed': '速度',
    ' Resistance': '耐性',
    ' Reserved': '予約量',
    ' Damage': 'ダメージ',
    ' Blocked': 'ブロック',
    ' Retaliation': '報復',
    ' Slowed Movement': '移動速度減少',
    ' Slower Enemy Attacks': '敵の攻撃減速',
    ' [fF]or (.+) Seconds?': 'を $1秒',
    ' Seconds? of ': '秒間',
    ' Cost': 'コスト',
    ' Meter Explosion Radius': 'm 爆発半径',
    ' Meter Radius': 'm 半径',
    'Projectiles?': '砲弾数',
    'Undead': 'アンデッド',
    'Aether Corruption': 'イーサーコラプション',
    'Aetherial': 'イセリアル',
    'Chthonic': 'クトーニック',
    // '': '人間',
    // '': 'ビースト',
    'Increases Armor by': '装甲強化',
    'to Cadence': 'カデンツ',
    'to Fighting Form': 'ファイティング フォーム',
    'to Deadly Momentum': 'デッドリー モメンタム',
    'to Discord': 'ディスコード',
    'to Forcewave': 'フォースウェイブ',
    'to Rending Force': 'レンディング フォース',
    'to Internal Trauma': 'インターナル トラウマ',
    'to Tremor': 'トレマー',
    'to Markovian\'s Advantage': 'マーコヴィアンのアドバンテッジ',
    'to Military Conditioning': 'ミリタリー コンディショニング',
    'to Menhir\'s Will': 'メンヒルの意志',
    'to Fighting Spirit': 'ファイティング スピリット',
    'to Shield Training': 'シールド トレーニング',
    'to Overguard': 'オーバーガード',
    'to Blitz': 'ブリッツ',
    'to Blindside': 'ブラインドサイト',
    'to Blade Arc': 'ブレイド アーク',
    'to Laceration': 'ラセレイション',
    'to Clean Sweep': 'クリーン スウィープ',
    'to Zolhan\'s Technique': 'ゾルハンのテクニック',
    'to Veterancy': 'ベテランシー',
    'to Field Command': 'フィールド コマンド',
    'to Squad Tactics': 'スクワッド タクティクス',
    'to War Cry': 'ウォー クライ',
    'to Break Morale': 'ブレイク モラル',
    'to Decorated Soldier': 'デコレイテッド ソルジャー',
    'to Scars of Battle': 'スカーズ オブ バトル',
    'to Counter Strike': 'カウンター ストライク',
    'to Menhir\'s Bulwark': 'メンヒルの防壁',
    'to Oleron\'s Rage': 'オレロンの激怒',
    'Soldier': 'ソルジャー',
    'to Flashbang': 'フラッシュバン',
    'to Searing Light': 'シーリング ライト',
    'to Vindictive Flame': 'ヴィンディクティヴ フレイム',
    'to Ulzuin\'s Wrath': 'ウルズインの怒り',
    'to Stun Jacks': 'スタン ジャックス',
    'to Full Spread': 'フル スプレッド',
    'to Grenado': 'グレネイド',
    'to High Impact': 'ハイ インパクト',
    'to Shattering Blast': 'シャタリング ブラスト',
    'to Quick Jacks': 'クイック ジャックス',
    'to Skyfire Grenado': 'スカイファイア グレネイド',
    'to Fire Strike': 'ファイア ストライク',
    'to Searing Might': 'シーリング マイト',
    'to Canister Bomb': 'キャニスター ボム',
    'to Improved Casing': 'インプルーヴド ケーシング',
    'to Explosive Strike': 'エクスプローシブ ストライク',
    'to Static Strike': 'スタティック ストライク',
    'to Brimstone': 'ブリムストン',
    'to Concussive Bomb': 'コンカッシヴ ボム',
    'to Searing Strike': 'シーリング ストライク',
    'to Mortar Trap': 'モーター トラップ',
    'to Heavy Ordnance': 'ヘビー オードナンス',
    'to "The Big One"': '"ザ ビッグ ワン"',
    'to Blackwater Cocktail': 'ブラックウォーター カクテル',
    'to Demon Fire': 'デーモン ファイア',
    'to Agonizing Flames': 'アゴナイジング フレイムズ',
    'to Blast Shield': 'ブラスト シールド',
    'to High Potency': 'ハイ ポウテンシー',
    'to Thermite Mine': 'テルミット マイン',
    'to Hellfire Mine': 'ヘルファイア マイン',
    'to Flame Touched': 'フレイム タッチ',
    'to Temper': 'テンパー',
    'to Ulzuin\'s Chosen': 'ウルズインの チョーズン',
    'Demolitionist': 'デモリッショニスト',
    'to Summon Familiar': 'サモン ファミリア',
    'to Mend Flesh': 'メンド フレッシュ',
    'to Storm Spirit': 'ストーム スピリット',
    'to Lightning Strike': 'ライトニング ストライク',
    'to Summon Hellhound': 'サモン ヘルハウンド',
    'to Ember Claw': 'エンバー クロウ',
    'to Hellfire': 'ヘルファイア',
    'to Infernal Breath': 'インファーナル ブレス',
    'to Curse of Frailty': 'カース オブ フレイルティー',
    'to Vulnerability': 'ヴァルネラビリティ',
    'to Sigil of Consumption': 'シジル オブ コンサンプション',
    'to Destruction': 'デストラクション',
    'to Dreeg\'s Evil Eye': 'ドリーグの邪眼',
    'to Blood Burst': 'ブラッド バースト',
    'to Terrifying Gaze': 'テリファイング ゲイズ',
    'to Terrify': 'テリファイ',
    'to Vile Eruption': 'ヴァイル イラプション',
    'to Blood of Dreeg': 'ドリーグの血',
    'to Aspect of the Guardian': 'アスペクト オブ ザ ガーディアン',
    'to Focused Gaze': 'フォーカスト ゲイズ',
    'to Bonds of Bysmiel': 'ビスミールの絆',
    'to Manipulation': 'マニピュレイション',
    'to Bloody Pox': 'ブラディ ポックス',
    'to Wasting': 'ウェイスティング',
    'to Black Death': 'ブラック デス',
    'to Doom Bolt': 'ドゥーム ボルト',
    'to Fevered Rage': 'フィーバード レイジ',
    'to Possession': 'ポゼッション',
    'to Solael\'s Witchfire': 'ソレイルのウィッチファイア',
    'to Second Rite': '第二儀式',
    'to Consecrated Blade': 'コンセクレイテッド ブレイド',
    'Occultist': 'オカルティスト',
    'to Veil of Shadow': 'ベール オブ シャドウ',
    'to Night\'s Chill': 'ナイツ チル',
    'to Phantasmal Armor': 'ファンタズマル アーマー',
    'to Amarasta\'s Blade Burst': 'アマラスタの ブレイド バースト',
    'to Lethal Assault': 'リーサル アサルト',
    'to Shadow Strike': 'シャドウ ストライク',
    'to Nidalla\'s Justifiable Ends': 'ニダラの ジャストファイアブル エンズ',
    'to Nightfall': 'ナイトフォール',
    'to Dual Blades': 'デュアル ブレイズ',
    'to Belgothian\'s Shears': 'ベルゴシアンの シーア',
    'to Nidalla\'s Hidden Hand': 'ニダラの ヒドゥン ハンド',
    'to Anatomy of Murder': 'アナトミー オブ マーダー',
    'to Amarasta\'s Quick Cut': 'アマラスタの クイック カット',
    'to Whirling Death': 'ホワーリング デス',
    'to Execution': 'エクセキューション',
    'to Blade Barrier': 'ブレイド バリア',
    'to Pneumatic Burst': 'ニューマチック バースト',
    'to Shadow Dance': 'シャドウ ダンス',
    'to Elemental Awakening': 'エレメンタル アウェイクニング',
    'to Ring of Steel': 'リング オブ スチール',
    'to Circle of Slaughter': 'サークル オブ スローター',
    'to Breath of Belgothian': 'ブレス オブ ベルゴシアン',
    'to Ring of Frost': 'リング オブ フロスト',
    'to Phantasmal Blades': 'ファンタズマル ブレイズ',
    'to Heart Seeker': 'ハート シーカー',
    'to Nether Edge': 'ネザー エッジ',
    'to Blade Trap': 'ブレイド トラップ',
    'to Devouring Blades': 'デヴァウリング ブレイズ',
    'to Frenetic Throw': 'フレネティック スロウ',
    'to Merciless Repertoire': 'マーシレス レペトワー',
    'to Blade Spirit': 'ブレイド スピリット',
    'Nightblade': 'ナイトブレイド',
    'to Inner Focus': 'イナー フォーカス',
    'to Arcane Will': 'アルケイン ウィル',
    'to Panetti\'s Replicating Missile': 'パネッティの 複製ミサイル',
    'to Distortion': 'ディストーション',
    'to Supercharged': 'スーパーチャージ',
    'to Proliferation': 'プロリフィレイション',
    'to Maiven\'s Sphere of Protection': 'メイヴェンの スフィア オブ プロテクション',
    'to Conversion': 'コンバージョン',
    'to Iskandra\'s Elemental Exchange': 'イスカンドラの エレメンタル エクスチェンジ',
    'to Overload': 'オーバーロード',
    'to Elemental Balance': 'エレメンタル バランス',
    'to Nullification': 'ナリフィケイション',
    'to Manifestation': 'マニフェステイション',
    'to Albrecht\'s Aether Ray': 'アルブレヒトの イーサー レイ',
    'to Disintegration': 'ディシンティグレイション',
    'to Olexra\'s Flash Freeze': 'オレクスラの フラッシュ フリーズ',
    'to Absolute Zero': 'アブソリュート ゼロ',
    'to Tainted Power': 'テインテッド パワー',
    'to Callidor\'s Tempest': 'キャリドアの テンペスト',
    'to Inferno': 'インフェルノ',
    'to Mental Alacrity': 'メンタル アラクリティ',
    'to Wrath of Agrivix': 'ラース オブ アグリヴィックス',
    'to Fabric of Reality': 'ファブリック オブ リアリティ',
    'to Trozan\'s Sky Shard': 'トロザンの スカイ シャード',
    'to Frozen Core': 'フローズン コア',
    'to Shattered Star': 'シャッタード スター',
    'to Star Pact': 'スター パクト',
    'to Mirror of Ereoctes': 'エレオクテスの鏡',
    'to Devastation': 'デヴァステイション',
    'to Reckless Power': 'レックレス パワー',
    'Arcanist': 'アルカニスト',
    'to Devouring Swarm': 'デヴァウリング スウォーム',
    'to Summon Briarthorn': 'サモン ブライアソーン',
    'to Ground Slam': 'グラウンド スラム',
    'to Emboldening Roar': 'エンボルデニング ローア',
    'to Savagery': 'サヴィジリィ',
    'to Tenacity of the Boar': 'テナシティ オブ ザ ボア',
    'to Storm Touched': 'ストーム タッチ',
    'to Wind Devil': 'ウィンド デビル',
    'to Raging Tempest': 'レイジング テンペスト',
    'to Maelstrom': 'メイルストロム',
    'to Might of the Bear': 'マイト オブ ザ ベア',
    'to Wendigo Totem': 'ウェンディゴ トーテム',
    'to Blood Pact': 'ブラッド パクト',
    'to Brute Force': 'ブルート フォース',
    'to Feral Hunger': 'フィラル ハンガー',
    'to Upheaval': 'アプヒーヴァル',
    'to Storm Totem': 'ストーム トーテム',
    'to Corrupted Storm': 'コラプテッド ストーム',
    'to Mogdrogen\'s Pact': 'モグドロゲンズ パクト',
    'to Heart of the Wild': 'ハート オブ ザ ワイルド',
    'to Oak Skin': 'オーク スキン',
    'to Primal Bond': 'プライマル ボンド',
    'to Grasping Vines': 'グラスピング ヴァインズ',
    'to Entangling Vines': 'エンタングリング ヴァインズ',
    'to Conjure Primal Spirit': 'カンジャー プライマル スピリット',
    'to Primal Strike': 'プライマル ストライク',
    'to Torrent': 'トーレント',
    'to Storm Surge': 'ストーム サージ',
    'to Stormcaller\'s Pact': 'ストームコーラーズ パクト',
    'to Thunderous Strike': 'サンダラス ストライク',
    'Skill Disruption Protection': 'スキル詠唱妨害防御',
    'Shaman': 'シャーマン',
    'Armor Piercing': '装甲貫通',
    'Total': '全',
    'Attack': '攻撃',
    'Casting': '詠唱',
    'Movement': '移動',
    'Health': 'ヘルス',
    'Energy': 'エナジー',
    'Life Leech': 'ライフ吸収',
    'Constitution': '活力',
    'Physique': '体格',
    'Cunning': '狡猾性',
    'Spirit': '精神',
    'Crit': 'クリティカル',
    'Slow': '減速',
    'Stun': '気絶',
    'Freeze': '凍結',
    'Confuse': '混乱',
    'Entrapment': '捕縛',
    'Petrify': '石化',
    'Light Radius': '照明半径',
    'Physical': '物理',
    'Internal Trauma': '体内損傷',
    'Fire': '火炎',
    'Burn': '燃焼',
    'Cold': '冷気',
    'Frostburn': '凍傷',
    'Lightning': '雷',
    'Electrocute': '感電',
    'Elemental': 'エレメンタル',
    'Poison & Acid': '毒酸',
    'Poison': '毒',
    'Acid': '酸',
    'Piercing': '刺突',
    'Pierce': '刺突',
    'Bleeding': '出血',
    'Vitality Decay': '生命力減衰',
    'Vitality': '生命力',
    'Aether': 'イーサー',
    'Chaos': 'カオス',
    'Level Requirement': '必要レベル',
    'ItemLevel': 'ｱｲﾃﾑﾚﾍﾞﾙ',
    'Item Level': 'アイテムレベル',
    'Level': 'レベル',
    'Filters': 'フィルター',
    'Base': '基礎値',
    'Name': '名前',
    'Slots': '装備',
    'Armor': '装甲',
    'Weapon': '武器',
    'Guns': '銃',
    'Pistols': '拳銃',
    'Rifles': 'ライフル',
    'Axes': '斧',
    'Maces': 'メイス',
    'Swords': '剣',
    'Two Handers': '両手持ち',
    'Shields': '盾',
    'Shield': 'シールド',
    'Focus': '詠唱者用オフハンド',
    'Daggers': 'ダガー',
    'Scepters': 'セプター',
    'Amulets': 'アミュレット',
    'Medals': 'メダル',
    'Rings': 'リング',
    'Waist': 'ベルト',
};

var Trans = {};
var keys = Object.keys(trans_table);
keys.forEach((key) => {
    var reg = new RegExp(key, 'g');
    Trans[key] = {
        reg: reg,
        rep: trans_table[key]
    };
});

export default Trans;
